name: collect data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install requests

      - name: Run collector
        run: python collect_sources.py
